"""Provider-neutral execution metadata for VibeCAD's Agent Core."""

from vibecad.execution.registry import (
    DEFAULT_OPERATION_REGISTRY,
    ExecutionProfile,
    FieldMetadata,
    OperationMetadata,
    OperationRegistry,
    RegistryError,
    RegistryErrorCode,
    ResourceBudget,
    ResultSlotMetadata,
    RiskClass,
    ValueShape,
)
from vibecad.execution.selectors import (
    EntityIdentity,
    EntityKind,
    Provenance,
    ProvenanceSource,
    SelectorError,
    SelectorErrorCode,
    SelectorV1,
    SemanticRole,
    encode_provenance_metadata,
    index_entity_identities,
    parse_entity_identity,
    resolve_selector,
)

__all__ = [
    "DEFAULT_OPERATION_REGISTRY",
    "EntityIdentity",
    "EntityKind",
    "ExecutionProfile",
    "FieldMetadata",
    "OperationMetadata",
    "OperationRegistry",
    "Provenance",
    "ProvenanceSource",
    "RegistryError",
    "RegistryErrorCode",
    "ResourceBudget",
    "ResultSlotMetadata",
    "RiskClass",
    "SelectorError",
    "SelectorErrorCode",
    "SelectorV1",
    "SemanticRole",
    "ValueShape",
    "encode_provenance_metadata",
    "index_entity_identities",
    "parse_entity_identity",
    "resolve_selector",
]
