"""Independent Mesh/SubD derived-artifact domain."""

from vibecad.organic.contracts import (
    AxisConvention,
    DerivedArtifact,
    DerivedArtifactKind,
    DerivedArtifactSet,
    MeshJobRequest,
    MeshMediaType,
    MeshOperation,
    MeshOperationKind,
    MeshOperationPlan,
    MeshProfile,
    MirrorAxis,
    OrganicContractError,
    OrganicContractErrorCode,
    SealedMeshSource,
)
from vibecad.organic.fake_adapter import (
    DeterministicFakeOrganicAdapter,
    FakeArtifactPayload,
    FakeOrganicAdapterError,
    FakeOrganicAdapterErrorCode,
    FakeOrganicFixture,
)
from vibecad.organic.plan import (
    MeshPlanError,
    MeshPlanErrorCode,
    MeshPlanSummary,
    mesh_operation_plan_digest,
    validate_mesh_operation_plan,
)
from vibecad.organic.validation import (
    MeshValidationError,
    MeshValidationErrorCode,
    MeshValidationReport,
    MeshValidationStatus,
    SelfIntersectionEvidence,
    mesh_content_digest,
    validate_mesh,
)

__all__ = [
    "AxisConvention",
    "DerivedArtifact",
    "DerivedArtifactKind",
    "DerivedArtifactSet",
    "DeterministicFakeOrganicAdapter",
    "FakeArtifactPayload",
    "FakeOrganicAdapterError",
    "FakeOrganicAdapterErrorCode",
    "FakeOrganicFixture",
    "MeshJobRequest",
    "MeshMediaType",
    "MeshOperation",
    "MeshOperationKind",
    "MeshOperationPlan",
    "MeshPlanError",
    "MeshPlanErrorCode",
    "MeshPlanSummary",
    "MeshProfile",
    "MeshValidationError",
    "MeshValidationErrorCode",
    "MeshValidationReport",
    "MeshValidationStatus",
    "MirrorAxis",
    "OrganicContractError",
    "OrganicContractErrorCode",
    "SealedMeshSource",
    "SelfIntersectionEvidence",
    "mesh_content_digest",
    "mesh_operation_plan_digest",
    "validate_mesh",
    "validate_mesh_operation_plan",
]
